# Generated by Django 3.0.3 on 2020-03-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musycweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='emax_lower',
            field=models.FloatField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='emax_upper',
            field=models.FloatField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='file',
            field=models.FileField(editable=False, upload_to='_state/datasets'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='metric_name',
            field=models.TextField(default='Percent effect', editable=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='orientation',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Emax<E0'), (1, 'Emax>E0')], default=1, editable=False),
        ),
    ]
