# Generated by Django 3.0.3 on 2020-03-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musycweb', '0002_emax_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='e0_lower',
            field=models.FloatField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='e0_upper',
            field=models.FloatField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='orientation',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Emax>E0'), (1, 'Emax<E0')], default=1, editable=False),
        ),
    ]
