# Generated by Django 3.0.3 on 2020-03-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musycweb', '0005_task_link_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasettask',
            name='batch',
            field=models.TextField(default=None, null=True),
        ),
    ]
