# Generated by Django 3.1 on 2020-10-22 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musycweb', '0010_auto_20201022_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musycweb.project'),
        ),
    ]
