# Generated by Django 3.1 on 2020-10-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musycweb', '0011_auto_20201022_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='project_id',
            new_name='project',
        ),
    ]
