# Generated by Django 3.1.4 on 2020-12-02 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musycweb', '0012_auto_20201022_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
